apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: videogen
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:16-alpine
        env:
        - name: POSTGRES_DB
          value: videogen
        - name: POSTGRES_USER
          value: videogen
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: videogen-pg-auth
              key: postgres-password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: videogen
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: videogen
spec:
  selector:
    app: postgresql
  ports:
  - port: 5432
    targetPort: 5432
